Add required inputs into default configuration
netglade/auto_mappr pull request #31
Opened 2023-04-20 09:02 UTC by petrnymsa

Address #30

2023-04-20 09:19 UTC, tenhobi requested changes

2023-04-20 09:19 UTC, tenhobi commented on packages/auto_mappr/CHANGELOG.md
> +- Add `required_inputs` with  `.freezed.dart` and `.drift.dart` by default
```suggestion
- Add `required_inputs` with `.freezed.dart` and `.drift.dart` by default.
```

2023-04-20 09:19 UTC, tenhobi commented on packages/auto_mappr/example/lib/freezed_example.dart
> +}
Is this used somewhere?

2023-04-20 09:22 UTC, petrnymsa commented on packages/auto_mappr/example/lib/freezed_example.dart
> +}
Removed

2023-04-20 11:15 UTC, tenhobi commented on packages/auto_mappr/CHANGELOG.md
> +## Unpublished
```suggestion
## Unreleased
```

2023-04-20 16:17 UTC, tenhobi requested changes

2023-04-21 06:37 UTC, petrnymsa commented on packages/auto_mappr/pubspec.yaml
>    json_serializable: ^6.6.1
I think tests should stay in generator package

2023-04-23 10:25 UTC, tenhobi commented on melos.yaml
> +  - examples/**
IMO we need both `examples/**` and `packages/**/example`.

2023-04-23 13:21 UTC, tenhobi approved these changes
![jiffy](https://user-images.githubusercontent.com/5287596/233842175-1112948d-6b17-4733-9802-d76a15ba6947.gif)

2023-04-23 20:52 UTC, merged