Add import aliases support
netglade/auto_mappr pull request #62
Opened 2023-04-29 21:02 UTC by tenhobi

Fixes #55

2023-05-02 09:34 UTC, tenhobi commented
- [ ] TODO (based on @DevNico feedback): we should test import alias that have export of some class with a class we want to use in a mapping.

Aka we should probably do a recursive lookup and add all exports (and their exports, ...) to match with the import alias.

2023-06-21 18:51 UTC, petrnymsa approved these changes

2023-06-21 18:52 UTC, petrnymsa requested changes
Did we solve mentiod issue with SDK types?

2023-06-21 18:53 UTC, tenhobi commented
Not yet. I have WIP on the imported exports and then I will look at the modules.

2023-06-23 10:18 UTC, petrnymsa approved these changes

2023-06-23 10:27 UTC, merged